# Generated by Django 6.0.3 on 2026-03-31 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OrgaoJulgador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_municipio_ibge', models.IntegerField(blank=True, null=True)),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(blank=True, max_length=256)),
                ('tipo_ato_principal', models.CharField(blank=True, choices=[('acordo_homologado', 'Acordo Homologado'), ('sentenca', 'Sentenca'), ('acordao', 'Acordao'), ('despacho', 'Despacho'), ('outro', 'Outro')], max_length=32)),
                ('decisao', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, choices=[('arquivado', 'Arquivado'), ('acordo_homologado', 'Acordo Homologado'), ('sentenciado', 'Sentenciado'), ('em_andamento', 'Em Andamento')], max_length=32)),
                ('desfecho', models.CharField(blank=True, choices=[('acordo_favoravel', 'Acordo Favoravel'), ('sentenca_procedente', 'Sentenca Procedente'), ('sentenca_parcialmente_procedente', 'Sentenca Parcialmente Procedente'), ('sentenca_improcedente', 'Sentenca Improcedente'), ('extinta', 'Extinta'), ('arquivado_sem_decisao', 'Arquivado Sem Decisao'), ('outro', 'Outro')], max_length=32)),
                ('resultado_reclamante', models.CharField(blank=True, choices=[('ganhou', 'Ganhou'), ('ganhou_parcial', 'Ganhou Parcial'), ('perdeu', 'Perdeu'), ('sem_decisao', 'Sem Decisao')], max_length=32)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custas_valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('palavras_chave', models.ManyToManyField(blank=True, default=list, to='core.palavrachave')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20)),
                ('tribunal', models.CharField(blank=True, max_length=32)),
                ('data_hora_ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('grau', models.CharField(blank=True, max_length=32)),
                ('data_ajuizamento', models.DateField(blank=True, null=True)),
                ('analise', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.analise')),
                ('assuntos', models.ManyToManyField(blank=True, default=list, to='core.assunto')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classe')),
                ('orgao_julgador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orgaojulgador')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('numero_processo', 'tribunal', 'grau'), name='uniq_datajud_numero_tribunal_grau')],
            },
        ),
    ]
