# Generated by Django 6.0.3 on 2026-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
