# Generated by Django 6.0.5 on 2026-05-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processo_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analise',
            name='decisao',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='analise',
            name='resumo',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
