# Generated by Django 6.0.5 on 2026-05-23 21:32

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_analise_decisao_alter_analise_resumo'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='analise',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
