# Generated by Django 6.0.5 on 2026-05-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analise_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='movimentos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
