# Generated by Django 6.0.5 on 2026-05-27 00:12

import core.models.processo
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_processo_movimentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='movimentos',
        ),
        migrations.AddField(
            model_name='processo',
            name='movimentos',
            field=core.models.processo.CompressedJSONField(blank=True, default=list),
        ),
    ]
